app_project:
    resource: "@AppBundle/Resources/config/routing/project.yml"
    prefix:   /project

app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /user

app_redeem:
    resource: "@AppBundle/Resources/config/routing/redeem.yml"
    prefix:   /redeem

